apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: react
  template:
    metadata:
      labels:
        run: react
    spec:
      containers:
      - name: react
        image: olivierdg1/articles:react
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: react-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    run: react
  ports:
  - port: 3000
    name: react
    targetPort: 3000
    nodePort: 30001