apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: server
  template:
    metadata:
      labels:
        run: server
    spec:
      containers:
      - name: server
        image: olivierdg1/articles:server
        ports:
          - containerPort: 10000
---
apiVersion: v1
kind: Service
metadata:
  name: server-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    run: server
  ports:
  - port: 10000
    name: server
    targetPort: 10000
    nodePort: 30002